### ISSUE TITLE
List z-index not working

### ISSUE THREAD

**Issue by sorxrob** [arturbien/React95#105]
![Capture](https://user-images.githubusercontent.com/13049130/76393947-95179a00-63af-11ea-9adb-6246c2be5a77.PNG)

As you can see in the image, the list items are under the window component. I've tried setting the zIndex of the window to 1 and the List to 2 but nothing worked. Is there a way to achieve this?

Also, is it possible to move the AppBar at the bottom of the page?

Thank you for this well made component.

**Comment by arturbien** [comment]
Hi! thanks for using our library ♥️ And yes of course you can style/position the components any way you want. Have you tried using bigger zIndex? or set bigger zIndex but on the whole `<AppBar />` instead of just the `<List />`?

If this doesn't work please upload your project to https://codesandbox.io/ . 
Then I will be able to help you out :)

**Comment by sorxrob** [comment]
> Hi! thanks for using our library ♥️ And yes of course you can style/position the components any way you want. Have you tried using bigger zIndex? or set bigger zIndex but on the whole `<AppBar />` instead of just the `<List />`?
> 
> If this doesn't work please upload your project to https://codesandbox.io/ .
> Then I will be able to help you out :)

Hey thanks for the fast reply!

Yes, adding the zIndex in the AppBar worked! Thank you.

![Capture](https://user-images.githubusercontent.com/13049130/76397626-62bd6b00-63b6-11ea-90e1-57e6925c52b5.PNG)
