### ISSUE TITLE
Add Windows 95 styled scrollbars

### ISSUE THREAD

**Issue by TristanWiley** [arturbien/React95#5]
Something like these would do
https://codepen.io/louh/pen/oZJQvm

**Comment by 1j01** [comment]
Hey, that's a pretty nice recreation you've found there!
I have one a nice one to look at over here too: https://github.com/1j01/os-gui
I use `::-webkit-scrollbar-track-piece:active` instead of `::-webkit-scrollbar-track:active` so it doesn't darken the background of the scrollbar track when dragging by the scrollbar handle.
Also, the cursor should be reset to `default` for the textarea case, which I'm now realizing I don't handle, even tho I have Notepad on [98.js.org](https://98.js.org). (Maybe it didn't always work that way, and chrome's updated?)

**Comment by arturbien** [comment]
Yeah @1j01 version looks better 😊 Let's hope our scrollbars won't be to big tho (we are using 2x thicker borders than in original Windows). And we have to make them themable somehow to match other color schemes 🤔

**Comment by arturbien** [comment]
closed by #190

**Comment by coltenunger** [comment]
hi! I'm trying to implement a scroll bar just like this on my portfolio site. I think it would look really cool! Any ideas on how to get it looking like @TristanWiley 's or @1j01 's? My site is just using simple html, css and js.
