### ISSUE TITLE
Add error (Blue Screen of Death) component

### ISSUE THREAD

**Issue by JB1905** [arturbien/React95#6]
Add error (Blue Screen of Death) component

**Comment by rwachtler** [comment]
Something similar to this? 😄 

![Blue screen of death - windows 9X](https://upload.wikimedia.org/wikipedia/commons/3/3b/Windows_9X_BSOD.png)
(Source: [Wikimedia Commons](https://commons.wikimedia.org/wiki/File:Windows_9X_BSOD.png))

**Comment by arturbien** [comment]
@rwachtler  I did something similar on my [personal website](https://expensive.toys/)  😎.  I am not sure if we should include something like this in React95 library since these 'blue screen' components would require totally different font and styles. Maybe we could possibly make MS-DOS  like UI components as a module of React95 or completely separate library
