### ISSUE TITLE
Cannot import Menu component

### ISSUE THREAD

**Issue by ReactGirl** [arturbien/React95#8]
The Start menu show in story components is not exportable, so I cant use as the example shown in StoryBook

Doing this way:

import {Menu} from 'react95'

Any suggestion?

**Comment by arturbien** [comment]
Sorry for that! The Menu component was made to only showcase how menu may be implemented, and the current story source only shows the <Menu /> element without actual code it contains. That's why we have to add a [addon-storysource](https://github.com/storybooks/storybook/tree/master/addons/storysource) so people can see actual code in it. For now, see how [<Menu /> element](https://github.com/arturbien/React95/blob/master/src/components/Menu/Menu.js) is implemented 😊
